-- Galeria & Ateliê — schema inicial (Fase 2)

CREATE TYPE public.catalog_status AS ENUM ('active', 'paused');
CREATE TYPE public.period_color AS ENUM ('sage', 'blush', 'mustard', 'coral');
CREATE TYPE public.user_role AS ENUM ('admin', 'user');

-- Perfis (admin via Google Auth na Fase 3)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role public.user_role NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.artworks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  year TEXT NOT NULL,
  period TEXT NOT NULL,
  period_color public.period_color NOT NULL DEFAULT 'sage',
  quote TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL,
  rotation NUMERIC(4, 2) NOT NULL DEFAULT 0,
  status public.catalog_status NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  badge TEXT,
  image_url TEXT NOT NULL,
  rotation NUMERIC(4, 2) NOT NULL DEFAULT 0,
  note TEXT NOT NULL DEFAULT '',
  status public.catalog_status NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX artworks_status_idx ON public.artworks (status);
CREATE INDEX artworks_period_idx ON public.artworks (period);
CREATE INDEX stickers_status_idx ON public.stickers (status);

-- Helpers
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.email, ''),
    CASE
      WHEN lower(NEW.email) = lower('raissabarros@alu.ufc.br') THEN 'admin'::public.user_role
      ELSE 'user'::public.user_role
    END
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artworks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stickers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "artworks_public_read_active"
  ON public.artworks FOR SELECT
  TO anon, authenticated
  USING (status = 'active' OR public.is_admin());

CREATE POLICY "artworks_admin_insert"
  ON public.artworks FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "artworks_admin_update"
  ON public.artworks FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "artworks_admin_delete"
  ON public.artworks FOR DELETE
  TO authenticated
  USING (public.is_admin());

CREATE POLICY "stickers_public_read_active"
  ON public.stickers FOR SELECT
  TO anon, authenticated
  USING (status = 'active' OR public.is_admin());

CREATE POLICY "stickers_admin_insert"
  ON public.stickers FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "stickers_admin_update"
  ON public.stickers FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "stickers_admin_delete"
  ON public.stickers FOR DELETE
  TO authenticated
  USING (public.is_admin());
