-- Galeria de fotos por cartela (detalhe do produto)

CREATE TABLE public.sticker_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sticker_id BIGINT NOT NULL REFERENCES public.stickers (id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX sticker_images_sticker_sort_idx
  ON public.sticker_images (sticker_id, sort_order);

ALTER TABLE public.sticker_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "sticker_images_public_read"
  ON public.sticker_images FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.stickers s
      WHERE s.id = sticker_id
        AND (s.status = 'active' OR public.is_admin())
    )
  );

CREATE POLICY "sticker_images_admin_insert"
  ON public.sticker_images FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

CREATE POLICY "sticker_images_admin_update"
  ON public.sticker_images FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY "sticker_images_admin_delete"
  ON public.sticker_images FOR DELETE
  TO authenticated
  USING (public.is_admin());

GRANT SELECT ON public.sticker_images TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.sticker_images TO authenticated;
